a,b=10,5
print(a)
print(b)
print('Addition: ',a+b)
print('Substraction: ',a-b)
print('Multiplication: ',a*b)
print('Division: ',a/b)
print('Mod/Rem: ',a%b)
print('Pow: ', a**b)
print('Floor div: ',a//b)